# Setup
title:               Title
tagline:             ''
description:         ''
url:                 'https://emmy-l.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Emmy Linden
  url:               
  email:             el4436@princeton.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
